name: Deploy to Heroku - 2.0

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku auth:whoami

    - name: Set Heroku remote
      run: |
        git remote remove heroku || true
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/tags-prediction.git

    - name: Deploy to Heroku
      run: git push heroku HEAD:main 
