name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v2
      
      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Étape 4 : Exécuter les tests
      - name: Run tests
        run: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=src --cov-report=xml
          
      # Étape 5 : Déployer sur Heroku
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "tags-prediction"
          heroku_email: "tom.dumerle@gmail.com"
